### ISSUE TITLE
Empty value for parameter 'owner'

### ISSUE THREAD

**Issue by adrianyadav** [Bash2/staticman-netlify-function#2]
Hi, thanks for moving staticman to netlify.

Just ran into this problem, see:  https://www.adrianyadav.com/.netlify/functions/staticman/adrianyadav-netlify/master/ and the repo is https://github.com/adrianyadav/adrianyadav-netlify

{"errorType":"HttpError","errorMessage":"Empty value for parameter 'owner': undefined","trace":["HttpError: Empty value for parameter 'owner': undefined","    at /var/task/node_modules/@octokit/rest/plugins/validate/validate.js:74:15","    at Array.forEach (<anonymous>)","    at /var/task/node_modules/@octokit/rest/plugins/validate/validate.js:42:12","    at Array.forEach (<anonymous>)","    at validate (/var/task/node_modules/@octokit/rest/plugins/validate/validate.js:15:23)"]}

Do you have any idea on what could be causing that?  As far as I can tell validate.js is a dependency of staticman. I tried using the latest version of staticman instead of 		"staticman": "eduardoboucas/staticman#2be29f7", but that couldn't find the github key from the env variable

**Comment by Bash2** [comment]
Hi @adrianyadav 

The url you provided is missing the username and the property name. So in your case the complete url is https://www.adrianyadav.com/.netlify/functions/staticman/adrianyadav/adrianyadav-netlify/master/comments/

The username is known internally in the staticman code as the owner, which would explain the error. However, it seems like the Netlify function is stuck in the error state, which is something I haven't seen before. I think redeploying or erasing the function and adding it again should reset it.

Also I noticed that you still have the staticman config named `staticman.sample.yml`. It should be named `staticman.yml` in order for the function to work 😄 

Let me know if this helps.

**Comment by adrianyadav** [comment]
Hi @Bash2 

Thanks for replying - I tried all your instructions - redeploying and erasing the function didn't work. I changed the name of the config file (forgot to do that). 

Still no luck:

https://www.adrianyadav.com/.netlify/functions/staticman/adrianyadav/adrianyadav-netlify/master/comments/

**Comment by Bash2** [comment]
Hi @adrianyadav 

I think I figured it out. The regex I was using for parsing the url didn't account for the slash at the end 🤦‍♂ 

So what you need is https://www.adrianyadav.com/.netlify/functions/staticman/adrianyadav/adrianyadav-netlify/master/comments without a slash after comments

Meanwhile, I will write a fix for this.

**Comment by adrianyadav** [comment]
@Bash2  woohoo.... can't believe it was that simple. All working now!
https://github.com/adrianyadav/adrianyadav-netlify/pull/6

Didn't even think to try without a / at the end, well spotted. I'll close this issue.

Many thanks for your help.

**Comment by Bash2** [comment]
@adrianyadav No problem. I fixed the regex so that it won't happen again. Closing issue.
